#!/bin/bash
# ::::::::::::::::::::::::::::::::::::::::::::.
# C H A N N E L  S I M U L A T O R
# `````````````````````````````````````````````
# TELEVISION BROADCAST SIMULATOR
# ©KEVAN PLEDGER 2023
# ::::::::::::::::::::::::::::::::::::::::::::.
#
# COMMERCIAL BLOCK SCRIPT
#    PLAYS A RANDOM NUMBER OF COMMERCIALS BETWEEN YOUR MINIMUM AND MAXIMUM VALUES AS DEFINED IN THE HEADER OF THIS CONFIG FILE. AFTER
# THE NUMBER OF DESIGNATED COMMERCIAL FILES HAS BEEN PLAYED, THE FUNCTION EXITS
# -----------------------------------------------------------------------------------

# VARIABLE CHEATSHEET
# $1 = $CS_INSTALL_PATH

# ANNOUNCE SCRIPT EXECUTION
echo "[INFO] RUNNING play_commercials.sh"

# RESET OUR CONF LOAD STATE TO CHECK FOR VALID CONFIGURATION FILE
CS_CONF_LOAD_STATE=0

# ALWAYS SOURCE OUR CONFIG FIRST!
source ""$1"/channel_simulator.cfg"

# ANNOUNCE CONFIG LOAD STATE
if [ $CS_CONF_LOAD_STATE -eq 1 ];
    then
        echo "[INFO] COMM SCRIPT ANNOUNCES CONF LOAD SUCCESS!"
    else
        echo "[WARNING] COMM SCRIPT FAILED TO LOAD CONFIGURATION!"
        echo "[DEBUG] INSTALLATION DIRECTORY EXPECTED AT:$1"
        echo "[DEBUG] GOT INSTALLATION DIRECTORY OF "$1"/channel_simulator.cfg"
fi

# ANNOUNCE STATE CHANGE TO CONSOLE
echo "----------- COMMERCIAL BLOCK STARTING -----------"

# CHANGE DIRECTORIES INTO COMMERCIALS DIRECTORY AND STORE THE FILENAMES
#    INTO AN ARRAY COMM_LIST
cd "$CS_COMM_DIR"

# ASSIGN THE FILEPATHS OF EACH FILE IN THE DIRECTORY TO AN ARRAY
CS_COMM_MASTERLIST=(*)

# GENERATE A RANDOM NUMBER BETWEEN CS_COMM_MIN AND CS_COMM_MAX WHICH WILL REPRESENT THE NUMBER
#    OF COMMERCIALS THAT WILL PLAY THIS BLOCK
CS_COMM_RAND_SEED=$(shuf -i "$CS_COMM_MIN-$CS_COMM_MAX" -n 1)

# ANNOUNCE NUMBER OF COMMERCIALS CHOSEN
echo "[INFO] COMMERCIALS THIS SEGMENT: $CS_COMM_RAND_SEED"
CS_COMM_COUNTER_1=0
    while [ "$CS_COMM_COUNTER_1" -ne "$CS_COMM_RAND_SEED" ]
        do
            # PULL A RANDOM LINE AND ADD IT TO OUR SELECTED ARRAY
            CS_COMM_PULLED+=("${CS_COMM_MASTERLIST[RANDOM % ${#CS_COMM_MASTERLIST[@]}]}")

            # INCREMENT THE COUNTER VARIABLE
            ((CS_COMM_COUNTER_1++))
        done

# LOOP OVER CS_COMM_PULLED AND PLAY EACH FILE.
CS_COMM_COUNTER_2=0
CS_COMM_ARR_MAX=${#CS_COMM_PULLED[@]}

for i in "${CS_COMM_PULLED[@]}"
	do	
        # GET OUR COMMERCIAL
		CS_COMM_SELECTED="${CS_COMM_PULLED[$CS_COMM_COUNTER_2]}"
        
        # ANNOUNCE COMMERCIAL NUMBER AND SELECTION TO CONSOLE
        echo "[DEBUG] PLAYING COMMERCIAL NUMBER: $CS_COMM_COUNTER_2"
        echo "[DEBUG] SELECTED FILE: $CS_COMM_SELECTED"
        echo "[DEBUG] BEGINNING PLAYBACK VIA: $CS_MEDIAPLAYER"

        # GET OUR RUNTIME
		CS_COMM_RUNTIME=$(mediainfo --Inform="General;%Duration%" "$CS_COMM_SELECTED")

        # RUNTIME IS IN MILLISECONDS - CHANGE TO SECONDS FOR TIMEOUT
        CS_COMM_RUNTIME=$(expr $CS_COMM_RUNTIME / 1000)
        
        # CALL DISPLAY VIDEO AND PASS THE SELECTED FILE FIRST AND THE SHOWS DIRECTORY AS THE SECOND ARGUMENT
        "$1"/display_video.sh "$CS_COMM_SELECTED" "$CS_COMM_DIR" "$1" "$CS_COMM_RUNTIME"

        # INCREMENT THE COUNTER
        CS_COMM_COUNTER_2=$(expr $CS_COMM_COUNTER_2 + 1)
	done

# PURGE PULLED COMMERCIAL ARRAY!
CS_COMM_PULLED=()

# ANNOUNCE END OF COMMERCIAL BLOCK TO CONSOLE
echo "----------- COMMERCIAL BLOCK ENDING -----------"

# AND EXIT
return