#!/bin/bash
# ::::::::::::::::::::::::::::::::::::::::::::.
# C H A N N E L  S I M U L A T O R
# `````````````````````````````````````````````
# TELEVISION BROADCAST SIMULATOR
# ©KEVAN PLEDGER 2023
# ::::::::::::::::::::::::::::::::::::::::::::.
#
# COMMERCIAL BLOCK SCRIPT
#    PLAYS A RANDOM NUMBER OF COMMERCIALS BETWEEN YOUR MINIMUM AND MAXIMUM VALUES AS DEFINED IN THE HEADER OF THIS CONFIG FILE. AFTER
# THE NUMBER OF DESIGNATED COMMERCIAL FILES HAS BEEN PLAYED, THE FUNCTION EXITS
#-----------------------------------------------------------------------------------
# ALWAYS SOURCE OUR CONFIG
source config/channel_simulator.cfg

# ANNOUNCE STATE CHANGE TO CONSOLE
echo "---BEGINNING COMMERCIAL BLOCK---"

# CHANGE DIRECTORIES INTO COMMERCIALS DIRECTORY AND STORE THE FILENAMES
#    INTO AN ARRAY COMM_LIST
cd "$CS_COMM_DIR"

# ASSIGN THE FILEPATHS OF EACH FILE IN THE DIRECTORY TO AN ARRAY
CS_COMM_MASTERLIST=(*)

# GENERATE A RANDOM NUMBER BETWEEN CS_COMM_MIN AND CS_COMM_MAX WHICH WILL REPRESENT THE NUMBER
#    OF COMMERCIALS THAT WILL PLAY THIS BLOCK
CS_COMM_RAND_SEED=$(shuf -i "$CS_COMM_MIN-$CS_COMM_MAX" -n 1)

# ANNOUNCE NUMBER OF COMMERCIALS CHOSEN
echo "COMMERCIALS THIS SEGMENT: $CS_COMM_RAND_SEED"
CS_COMM_COUNTER_1=0
    while [ "$CS_COMM_COUNTER_1" -ne "$CS_COMM_RAND_SEED" ]
        do
            # PULL A RANDOM LINE AND ADD IT TO OUR SELECTED ARRAY
            CS_COMM_PULLED+=("${CS_COMM_MASTERLIST[RANDOM % ${#CS_COMM_MASTERLIST[@]}]}")

            # INCREMENT THE COUNTER VARIABLE
            ((CS_COMM_COUNTER_1++))
        done

# LOOP OVER CS_COMM_PULLED AND PLAY EACH FILE.
CS_COMM_COUNTER_2=0
CS_COMM_ARR_MAX=${#CS_COMM_PULLED[@]}

for i in "${CS_COMM_PULLED[@]}"
	do	
        # GET OUR COMMERCIAL
		CS_COMM_SELECTED="${CS_COMM_PULLED[$CS_COMM_COUNTER_2]}"
        
        # ANNOUNCE COMMERCIAL NUMBER AND SELECTION TO CONSOLE
        echo "PLAYING COMMERCIAL NUMBER: $CS_COMM_COUNTER_2"
        echo "SELECTED FILE: $CS_COMM_SELECTED"
        echo "BEGINNING PLAYBACK VIA: $CS_MEDIAPLAYER"

        # GET OUR RUNTIME
		CS_COMM_RUNTIME=$(mediainfo --Inform="General;%Duration%" "$CS_COMM_SELECTED")

        # RUNTIME IS IN MILLISECONDS - CHANGE TO SECONDS FOR TIMEOUT
        CS_COMM_RUNTIME=$(expr $CS_COMM_RUNTIME / 1000)
        echo "value of cs_comm_mediaplayer is: $CS_COMM_MEDIAPLAYER"
        
		# PLAY OUR COMMERCIAL
        if [[ "$CS_MEDIAPLAYER" = 'vlc' ]];
        then
                # IF OUR MEDIAPLAYER IS VLC WE ARE FIRST CLASS!
                timeout $CS_COMM_RUNTIME "$CS_MEDIAPLAYER" -I dummy --fullscreen --qt-minimal-view --no-qt-name-in-title --no-video-deco --no-embedded-video "$CS_COMM_SELECTED"
                #timeout 10s "$CS_MEDIAPLAYER" -I dummy --fullscreen --qt-minimal-view --no-qt-name-in-title --no-video-deco --no-embedded-video "$CS_COMM_SELECTED"

        else
                # OTHERWISE ASSUME STANDARD MEDIA PLAYER
		        #timeout 5s "$CS_MEDIAPLAYER" "$CS_COMM_SELECTED"
                timeout $CS_COMM_RUNTIME "$CS_MEDIAPLAYER" "$CS_COMM_SELECTED"
        fi

        # INCREMENT THE COUNTER
        CS_COMM_COUNTER_2=$(expr $CS_COMM_COUNTER_2 + 1)
	done

# PURGE PULLED COMMERCIAL ARRAY!
CS_COMM_PULLED=()

# ANNOUNCE END OF COMMERCIAL BLOCK TO CONSOLE
echo "---COMMERCIAL BLOCK FINISHED---"

# AND EXIT
return