#!/bin/bash
# ::::::::::::::::::::::::::::::::::::::::::::.
# C H A N N E L  S I M U L A T O R
# `````````````````````````````````````````````
# TELEVISION BROADCAST SIMULATOR
# ©KEVAN PLEDGER 2023
# ::::::::::::::::::::::::::::::::::::::::::::.
#
# CONFIGURATION LOADER SCRIPT
#    LOADS CONFIGURATION FILES FROM ~/config AND SETS ENVIRONMENT
# VARIABLES NECESSARY FOR THE OPERATION OF CHANNEL SIMULATOR!


# ANNOUNCE STATE CHANGE TO CONSOLE
echo "---READING CONFIGURATION FILE---"
	
# CHECK FOR EXISTENCE OF CONFIG FILE!
if ! test -f $CS_CONFIG_FILE;
	then
		echo "MISSING OR INVALID CONFIGURATION FILE!"
	else
		# ANNOUNCE DISCOVERY OF CONFIG FILE
		echo "CHANNEL SIM CONFIG FILE FOUND AT:"
		echo "$CS_CONFIG_FILE"

		# SOURCE THE CONFIG FILE TO SET THE VARIABLES
		source "$CS_CONFIG_FILE"

		# ANNOUNCE DETECTIONS
		echo "MODE SELECTION: $CS_MODE"
        echo "MEDIA PLAYER: $CS_MEDIAPLAYER"

fi

